### ISSUE TITLE
Labaler fails on vt file

### ISSUE THREAD

**Issue by Acuicui71** [malicialab/avclass#19]
first, the The contents of 1.vt.json is 
 {
    "md5":"b68abd064e975e1c6d5f25e748663076",
    
"permalink":"https://www.virustotal.com/file/d6c47eba7f3e3bb36ab273cb251d08efcd1c42181d85ad433f8a00a7bda0ecd6/analysis/1579101960/",
    "positives":66,
    "resource":"b68abd064e975e1c6d5f25e748663076",
    "response_code":1,
    "scan_date":"2020-01-15 15:26:00",
    "scan_id":"d6c47eba7f3e3bb36ab273cb251d08efcd1c42181d85ad433f8a00a7bda0ecd6-1579101960",
    "scans":{
        "ALYac":{
            "detected":true,
            "result":"Generic.DataStealer.1.1ACBA8F0",
            "update":"20200115",
            "version":"1.1.1.5"
        },
        "APEX":{
            "detected":true,
            "result":"Malicious",
            "update":"20200113",
            "version":"5.105"
        },
        "AVG":{
            "detected":true,
            "result":"Sf:Crypt-AQ [Trj]",
            "update":"20200115",
            "version":"18.4.3895.0"
        },
        "Acronis":{
            "detected":true,
            "result":"suspicious",
            "update":"20200113",
            "version":"1.1.1.58"
        },
        "Ad-Aware":{
            "detected":true,
            "result":"Generic.DataStealer.1.1ACBA8F0",
            "update":"20200115",
            "version":"3.0.5.370"
        },
        "AegisLab":{
            "detected":true,
            "result":"Trojan.Win32.Generic.mtwx",
            "update":"20200115",
            "version":"4.2"
        },
        "AhnLab-V3":{
            "detected":true,
            "result":"Trojan/Win32.Tepfer.R142848",
            "update":"20200115",
            "version":"3.17.0.26111"
        },
        "Alibaba":{
            "detected":true,
            "result":"TrojanPSW:Win32/Tepfer.89e78928",
            "update":"20190527",
            "version":"0.3.0.5"
        },
        "Antiy-AVL":{
            "detected":true,
            "result":"Trojan[PSW]/Win32.Tepfer",
            "update":"20200115",
            "version":"3.0.0.1"
        },
        "Arcabit":{
            "detected":true,
            "result":"Generic.DataStealer.1.1ACBA8F0",
            "update":"20200115",
            "version":"1.0.0.869"
        },
        "Avast":{
            "detected":true,
            "result":"Sf:Crypt-AQ [Trj]",
            "update":"20200115",
            "version":"18.4.3895.0"
        },
        "Avast-Mobile":{
            "detected":false,
            "result":null,
            "update":"20200114",
            "version":"200114-00"
        },
        "Avira":{
            "detected":true,
            "result":"TR/Kryptik.avp.8",
            "update":"20200115",
            "version":"8.3.3.8"
        },
        "Baidu":{
            "detected":true,
            "result":"Win32.Trojan-PSW.Fareit.a",
            "update":"20190318",
            "version":"1.0.0.2"
        },
        "BitDefender":{
            "detected":true,
            "result":"Generic.DataStealer.1.1ACBA8F0",
            "update":"20200115",
            "version":"7.2"
        },
        "BitDefenderTheta":{
            "detected":true,
            "result":"Gen:NN.ZexaF.34082.gqW@aiYxzmi",
            "update":"20200113",
            "version":"7.2.37796.0"
        },
        "Bkav":{
            "detected":true,
            "result":"W32.AIDetectVM.malware",
            "update":"20200115",
            "version":"1.3.0.9899"
        },
        "CAT-QuickHeal":{
            "detected":true,
            "result":"Trojanpws.Tepfer.20314",
            "update":"20200115",
            "version":"14.00"
        },
        "CMC":{
            "detected":false,
            "result":null,
            "update":"20190321",
            "version":"1.1.0.977"
        },
        "ClamAV":{
            "detected":true,
            "result":"Win.Trojan.Fareit-403",
            "update":"20200115",
            "version":"0.102.1.0"
        },
        "Comodo":{
            "detected":true,
            "result":"TrojWare.Win32.PWS.Fareit.GS@5t8zib",
            "update":"20200115",
            "version":"31966"
        },
        "CrowdStrike":{
            "detected":true,
            "result":"win/malicious_confidence_100% (W)",
            "update":"20190702",
            "version":"1.0"
        },
        "Cybereason":{
            "detected":true,
            "result":"malicious.64e975",
            "update":"20190616",
            "version":"1.2.449"
        },
        "Cylance":{
            "detected":true,
            "result":"Unsafe",
            "update":"20200115",
            "version":"2.3.1.101"
         }
    },
   "sha1":"59ff77b7f922891fa5c66ed1a8bbb964cd336119",
    "sha256":"d6c47eba7f3e3bb36ab273cb251d08efcd1c42181d85ad433f8a00a7bda0ecd6",
    "total":72,
    "verbose_msg":"Scan finished, information embedded"
}
second, I executed this statement
./avclass_labeler.py -vt data/1.vt.json -v > malheurReference.labels
but, I got a result
[-] Using aliases in /home/cuicui/下载/avclass-master/data/default.aliases
[-] Using generic tokens in /home/cuicui/下载/avclass-master/data/default.generics
[-] Processing input file data/1.vt.json
[-] 0 JSON readTraceback (most recent call last):
  File "./avclass_labeler.py", line 457, in <module>
    main(args)
  File "./avclass_labeler.py", line 117, in main
    vt_rep = json.loads(line)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 2 (char 1)

**Comment by malicialab** [comment]
Hi,

The input for AVClass is a file where each line is a whole JSON. In 
other words, you need to convert your JSON to be a one-liner. There are 
tons of tools for doing this depending on your OS. An example online 
tool if you want to test it:

https://tools.knowledgewalls.com/online-multiline-to-single-line-converter

Copy your 1.vt.json, convert it, copy the output string into another 
file, and pass it as input to AVClass. Should work fine (I just tested it)

Please close the issue if this addresses it

**Comment by Acuicui71** [comment]
Thank you for your reply, the problem has been solved
