### ISSUE TITLE
Labaler fails on invalid vt file

### ISSUE THREAD

**Issue by GenaBitu** [malicialab/avclass#2]
While running command:
```bash
./avclass_labeler.py -vt filename.vt.json | cat
```
on file:
```json
{
  "response_code": 0,
  "resource": "647739e7c3b617c4b409cc121b9adc4579b99c658098c136f85c0a3b42275419",
  "verbose_msg": "The requested resource is not among the finished, queued or pending scans"
}
```
I got this error:
```bash
[-] Using aliases in data/default.aliases
[-] Using generic tokens in data/default.generics
[-] 0 JSON readTraceback (most recent call last):
  File "./avclass_labeler.py", line 396, in <module>
    main(args)
  File "./avclass_labeler.py", line 86, in main
    name = getattr(sample_info, hash_type)
AttributeError: 'NoneType' object has no attribute 'md5'
```
The input file is part of a larger dataset which I am trying to batch process using avclass and it fails halfway because of these "invalid" files.

**Comment by GenaBitu** [comment]
And also for this file:
```json
[]
```

**Comment by malicialab** [comment]
It seems that the easiest solution is for you to remove those failed records from your input file. 
We may tweak the parser to ignore such errors and print them to file, but for now failing allows you to clean your input file.

Juan

**Comment by malicialab** [comment]
A fix for this issue has been committed
