### ISSUE TITLE
v.3 VT files are not processed

### ISSUE THREAD

**Issue by SBflying** [malicialab/avclass#28]
Hi, first, thank you for this awesome piece of code!
I have a bunch of v.3 VT jsons that I want to run through AVClass2. I've downloaded the module from your master branch to my ubuntu machine, however, it won't process my files and I don't know why...

**When I run AVClass2 on your VT v.2 example it works fine:**
`/home/shay/PycharmProjects/avclass-master$ ./avclass2/avclass2_labeler.py -vt ./examples/vtv2_sample.json -p`
`[-] Using tagging rules in /home/shay/PycharmProjects/avclass-master/avclass2/data/default.tagging`
`[-] Using taxonomy in /home/shay/PycharmProjects/avclass-master/avclass2/data/default.taxonomy`
`[-] Using expansion tags in /home/shay/PycharmProjects/avclass-master/avclass2/data/default.expansion`
`[-] Processing input file ./examples/vtv2_sample.json`
`[-] 0 JSON read602695c8f2ad76564bddcaf47b76edff 52      FAM:zeroaccess|19,FILE:os:windows|16,BEH:server|8,CLASS:backdoor|8,FILE:packed|7
f117cc1477513cb181cc2e9fcaab39b2        39      CLASS:rogueware|15,BEH:alertuser|15,FILE:os:windows|11,FAM:winwebsec|4,CLASS:grayware|4,CLASS:grayware:tool|3,FILE:packed|3`
`[-] 2 JSON read`
`[-] Samples: 2 NoScans: 0 NoTags: 0 GroundTruth: 0`

**However, When I run AVClass2 on your VT v.3 example it indicates that it is not able to process it:**
`/home/shay/PycharmProjects/avclass-master$ ./avclass2/avclass2_labeler.py -vt ./examples/vtv3_sample.json -p`
`[-] Using tagging rules in /home/shay/PycharmProjects/avclass-master/avclass2/data/default.tagging`
`[-] Using taxonomy in /home/shay/PycharmProjects/avclass-master/avclass2/data/default.taxonomy`
`[-] Using expansion tags in /home/shay/PycharmProjects/avclass-master/avclass2/data/default.expansion`
`[-] Processing input file ./examples/vtv3_sample.json`
`[-] 0 JSON read
Could not process: { "data": { "attributes": { "creation_date": 1584397860, "exiftool": { "Author": "Tatyana", "Characters": 1896, "CharactersWithSpaces": 2224, "CreateDate": "2020:03:16`
`.`
`.`
`.`
`"type": "file" } }`

`[-] 1 JSON read`
`[-] Samples: 1 NoScans: 1 NoTags: 1 GroundTruth: 0`

**Same thing happen when I use AVClass (instead of AVClass2).**

**What am I doing wrong?**

**Comment by malicialab** [comment]
Hi there,
To use as input v3 JSONs you need to provide the -vt3 command line option

./avclass2/avclass2_labeler.py -vt ./examples/vtv2_sample.json -p -vt3 > output.txt

(same for AVClass)

I have edited the README to add example command line options with all input formats in case it was not clear enough
If this fixes your problem, please close the issue

Best regards and happy new year!

**Comment by SBflying** [comment]
Thank you for your quick and helpful response!! it is now running smoothly
