### ISSUE TITLE
PUP tag labeling bug

### ISSUE THREAD

**Issue by yigitcankaya** [malicialab/avclass#43]
The function returns None instead of returning False, when there's no tag information. This causes the corresponding output line to not include the PUP label, instead of including 0.

https://github.com/malicialab/avclass/blob/a10aa4ae07b9315153725e6f2c0e55cf06b75ea4/avclass/common.py#L432

**Comment by malicialab** [comment]
Right, it is better to always return a Boolean using the standard rule of "not PUP unless we can determine otherwise"
Fixed!
