### ISSUE TITLE
Description of some taxonomies

### ISSUE THREAD

**Issue by whyisyoung** [malicialab/avclass#45]
Hi,

Thank you for the great work! 
I'm a bit unsure about some of the taxonomies, e.g., `BEH:facebook`, `BEH:files`, `BEH:google`, `BEH:search`,  "FAM:1000years". Could you please tell me more about these term?
Or is there a way to systematically find the explanation for these terms?
I tried MISP taxonomy but didn't have a luck.

Thank you for your help in advance!

**Comment by malicialab** [comment]
The BEH tags capture behaviors. BEH:facebook and BEH:google likely capture that these services are targeted by the malware. For example, BEH:facebook appears often together with FAM:koobface, a malware known to target Facebook (among other services). 
Regarding BEH:files, it is not very descriptive but it captures that the malware affects existing files or creates many new ones. This tag most often appears together with CLASS:virus and CLASS:worm
FAM:1000years seems to be an infrequent malware family. Some possible aliases for this family are "15years" and "earthsurvival"

**Comment by whyisyoung** [comment]
Thank you so much for the explanation. These are super helpful!
