### ISSUE TITLE
Division-by-zero error on `output_stats` function (file `labeler.py`)

### ISSUE THREAD

**Issue by ricardojrdez** [malicialab/avclass#46]
The `output_stats` function in line 482, file `labeler.py`, provokes a division-by-zero error when calculating stats from a JSON report with 0 malicious tags (variable `num_maltagged`):

```
frac = float(count) / float(num_maltagged) * 100
```

It can be simply fixed, for instance:

```
frac = 0
if num_maltagged > 0:
    frac = float(count) / float(num_maltagged) * 100
```

**Comment by malicialab** [comment]
Thanks for the report Ricardo. Should be fixed in new release 2.8.8
