### ISSUE TITLE
Understanding alias

### ISSUE THREAD

**Issue by b00108011** [malicialab/avclass#9]
Hi
I need some help understanding aliases please... (The link to join the mailing list fails with a 'forbidden' error.)
I thought that the first two columns (t1 and t2) represent the main family and alias name respectively..

but...

I am seeing records with (for example)

t1 = razy
t2 = score
and
t1 = score
t2 = razy

I need to be able to reduce all aliases to their main/master/root family names. Is this possible (and if so how). 

Thanks in advance

**Comment by b0urb0n** [comment]
To my understanding, the aliases work by associating  multiple known families to a "master" family.  Example from `avclass/data/default.aliases`:
```
panda zbot
zbocheman zbot
zeus zbot
```
This essentially means "if you see the following families: `panda`, `zbocheman`, or `zeus`, I want you to actually label this sample as `zbot`".  The alias (on the left) "points to" the _real_ family on the right.

**Comment by malicialab** [comment]
Sorry for never addressing this. b0urb0n comment is correct and it seems to cover the issue, so closing it.
